export const authConstants ={
    LOGIN_REQUEST : 'LOGIN_REQUEST',
    LOGIN_SUCCESS : 'LOGIN_SUCCESS',
    LOGIN_FAILURE : 'LOGIN_FAILURE',
    LOGOUT_REQUEST : 'LOGOUT_REQUEST',
    LOGOUT_SUCCESS : 'LOGOUT_SUCCESS',
    LOGOUT_FAILURE : 'LOGOUT_FAILURE',
}
export const userConstants ={
    USER_REGISTER_REQUEST: 'USER_REGISTER_REQUEST',
    USER_REGISTER_SUCCESS: 'USER_REGISTER_SUCCESS',
    USER_REGISTER_FAILURE: 'USER_REGISTER_FAILURE',
}
export const blogConstants = {

    GET_ALL_BLOG_REQUEST:'GET_ALL_BLOG_REQUEST',
    GET_ALL_BLOG_SUCCESS:'GET_ALL_BLOG_SUCCESS',
    GET_ALL_BLOG_FAILURE:'GET_ALL_BLOG_FAILURE',

    ADD_NEW_BLOG_REQUEST:'ADD_NEW_BLOG_REQUEST',
    ADD_NEW_BLOG_SUCCESS:'ADD_NEW_BLOG_SUCCESS',
    ADD_NEW_BLOG_FAILURE:'ADD_NEW_BLOG_FAILURE',

    UPDATE_BLOG_REQUEST:'UPDATE_BLOG_REQUEST',
    UPDATE_BLOG_SUCCESS:'UPDATE_BLOG_SUCCESS',
    UPDATE_BLOG_FAILURE:'UPDATE_BLOG_FAILURE',
    
    DELETE_BLOG_REQUEST:'DELETE_BLOG_REQUEST',
    DELETE_BLOG_SUCCESS:'DELETE_BLOG_SUCCESS',
    DELETE_BLOG_FAILURE:'DELETE_BLOG_FAILURE',

    DELETE_BLOG_BY_ID_REQUEST:'DELETE_BLOG_BY_ID_REQUEST',
    DELETE_BLOG_BY_ID_SUCCESS:'DELETE_BLOG_BY_ID_SUCCESS',
    DELETE_BLOG_BY_ID_FAILURE:'DELETE_BLOG_BY_ID_FAILURE'
}

export const initialDataConstants = {
    GET_ALL_INITIALDATA_REQUEST:'GET_ALL_INITIALDATA_REQUEST',
    GET_ALL_INITIALDATA_SUCCESS:'GET_ALL_INITIALDATA_SUCCESS',
    GET_ALL_INITIALDATA_FAILURE:'GET_ALL_INITIALDATA_FAILURE',
}